export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/611mRs-imxL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Red',
      price: '58999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro Max",
      imgSrc: 'https://m.media-amazon.com/images/I/712mZ6RXCQL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '47399',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/415gV21fNCL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '26499',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/315vs3rLEZL._SY445_SX342_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 13 (128GB) - Green',
      price: '52,999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '49999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 15",
      imgSrc: 'https://m.media-amazon.com/images/I/71v2jVh6nIL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 15 (128GB) - Pink',
      price: '72299',
    },
    {
      id: 12,
      category: 'tablets',
      title: "Apple iPad Pro 11″ (4th Generation)",
      imgSrc: 'https://m.media-amazon.com/images/I/81S05k6p0xL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/417PL2mg8+L._SX300_SY300_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '60190',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/61vsK7h3zVL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '22999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "HP Pavilion Gaming Laptop 11th Gen",
      imgSrc: 'https://m.media-amazon.com/images/I/51D0RrFXFEL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'HP Pavilion Gaming 11th Gen Intel Core i5 15.6"(39.6cm) FHD Gaming Laptop (8GB RAM/512GB SSD/RTX 3050 4GB Graphics/144 Hz/B&O/Windows 10 Home/MS Office/2.23Kg), 15-dk2012TX, Black ',
      price: '68999',
    },
    {
      id: 11,
      category: 'mobiles',
      title: "Realme 11 Pro+ 5G",
      imgSrc: 'https://m.media-amazon.com/images/I/41X7oqvBlML._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'realme 11 Pro+ 5G (Astral Black, 8GB RAM, 256GB Storage) | 120 Hz Curved Display | 200MP Prolight Camera | 7050 5G Dimensity | 100W SUPERVOOC | 12GB Dynamic RAM | Premier Vegan Leather Finish Design ',
      price: '29999',
    }, 
    {
      id: 15,
      category: 'laptops',
      title: "ASUS ROG Flow X13",
      imgSrc: 'https://m.media-amazon.com/images/I/61mI-ghw8mL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'ASUS ROG Flow X13 (2022), 13.4" (34.03 cm) FHD+ 16:10, 120Hz Touch, AMD Ryzen 9 6900HS,4GB RTX 3050 Graphics, 2-in-1 Gaming Laptop (16GB/512GB SSD/Win 11/Office 2021/Black/1.3 Kg), GV301RC-LJ132WS',
      price: '84990',
    },
     {
      id: 13,
      category: 'tablets',
      title: "OnePlus Pad",
      imgSrc: 'https://m.media-amazon.com/images/I/51oj5gE7P+L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'OnePlus Pad Go 28.85cm (11.35 inch) 2.4K 7:5 Ratio ReadFit Eye Care LCD Display, Dolby Atmos Quad Speakers,4G LTE(Calling) + Wi-Fi Connectivity Tablet, 8GB RAM 256 GB Storage Expandable Up-to 1TB' ,
      price: '23999',
    }, {
      id: 10,
      category: 'mobiles',
      title: "Samsung Galaxy S20 FE 5G",
      imgSrc: 'https://m.media-amazon.com/images/I/81vDZyJQ-4L._SY741_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: ' Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM, 128GB Storage)',
      price: '27996',
    },
    {
      id: 14,
      category: 'laptops',
      title: "Lenovo IdeaPad 1",
      imgSrc: 'https://m.media-amazon.com/images/I/71bDJ9wxxWL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Lenovo IdeaPad 1 AMD Ryzen 5 5500U 15.6" HD Thin and Light Laptop (16GB/512GB SSD/Windows 11 Home/MS Office 2021/Cloud Grey/1.61Kg), 82R400ERIN',
      price: '40990',
    },
    {
      id: 16,
      category: 'mobiles',
      title: "Samsung Galaxy S24 Ultra 5G AI Smartphone",
      imgSrc: 'https://m.media-amazon.com/images/I/81njZjDqc6L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: ' Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Gray, 12GB, 1TB Storage)',
      price: '159999',
    },
    {
      id: 15,
      category: 'laptops',
      title: "Lenovo V15 ",
      imgSrc: 'https://m.media-amazon.com/images/I/31uLEZHhMDL._SX522_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: ' Lenovo V15 Intel Celeron N4500 15.6" (39.62 cm) FHD (1920x1080) Antiglare 250 Nits Thin and Light Laptop (8GB RAM/256GB SSD/Windows 11 Home/Black/1Y Onsite/1.7 kg), 82QYA00MIN',
      price: '21600',
    },
    {
      id: 13,
      category: 'tablets',
      title: "Apple iPad (10th Generation)",
      imgSrc: 'https://m.media-amazon.com/images/I/61uA2UVnYWL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple iPad (10th Generation): with A14 Bionic chip, 27.69 cm (10.9″) Liquid Retina Display, 64GB, Wi-Fi 6, 12MP front/12MP Back Camera, Touch ID, All-Day Battery Life – Blue',
      price: '36900',
    }
  ]